### PR TITLE
Wireeditors

### PR DESCRIPTION
**Pull request by vipul12agarwal**

### CODE REVIEW

**Comment by arpitbansalsre** [comment]
Please remove thread.sleep and add explicit wait in your changes.

**Review by arpitbansalsre — CHANGES_REQUESTED** [review]
Please remove thread.sleep and add explicit wait in your changes.

**Comment by Rakunanthanks** [comment]
> Please remove thread.sleep and add explicit wait in your changes.

Now I have Removed Thread.sleep and added wait. Please let me know if any changes needed still.

**Comment by Rakunanthanks** [comment]
Revamped in another branch

**Pull request closed without merging**
